<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>ManimalLighthouse</AssemblyName>
    <Version>$(ModVersion)</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/manimal_lighthouse_rain.bundle" LogicalName="Manimal.Lighthouse.Rain.bundle" />
    <EmbeddedResource Include="Resources/manimal_lighthouse_keeper.bundle" LogicalName="Manimal.Lighthouse.Keeper.bundle" />
    <EmbeddedResource Include="Resources/legacy-quest-triggers.json" LogicalName="Manimal.Lighthouse.LegacyQuestTriggers.json" />
    <EmbeddedResource Include="Resources/keeper-restore.json" LogicalName="Manimal.Lighthouse.Keeper.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../lighthouse-shared/lighthouse-shared.csproj" />
    <Reference Include="UniTask">
      <HintPath>$(SPTPath)/BepInEx/plugins/UnityToolkit/UniTask.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(GameManaged)/UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ZLinq">
      <HintPath>$(SPTPath)/BepInEx/plugins/UnityToolkit/ZLinq.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(SPTPath)/BepInEx/core/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="JetBrains.Annotations">
      <HintPath>$(SPTPath)/SPT_Runtime/JetBrains.Annotations.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SPTPath)/BepInEx/core/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="spt-common">
      <HintPath>$(SPTPath)/BepInEx/plugins/spt/spt-common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="spt-reflection">
      <HintPath>$(SPTPath)/BepInEx/plugins/spt/spt-reflection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManaged)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>$(GameManaged)/Comfort.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Comfort.Unity">
      <HintPath>$(GameManaged)/Comfort.Unity.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Meta.XR.Audio">
      <HintPath>$(GameManaged)/Meta.XR.Audio.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameManaged)/Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManaged)/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManaged)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GameManaged)/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GameManaged)/UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>$(GameManaged)/UnityEngine.TerrainModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(GameManaged)/UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="JBooth.MicroSplat.Core">
      <HintPath>$(GameManaged)/JBooth.MicroSplat.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GameManaged)/UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
